### ISSUE TITLE
Can I run sparse group lasso in you package

### ISSUE THREAD

**Issue by ZoeTan** [YaohuiZeng/grpregOverlap#1]
Hi, Dr. Zeng
your packages is vey good to fit large scale data. but can I run sparse group lasso in your package?
I want to try GLM and cox regression.

Thanks
Zoe

**Comment by ZoeTan** [comment]
I run sparse group lasso in R packages SGL. but when the p>>n, such as p=1000, the speed is very slow.

**Comment by YaohuiZeng** [comment]
If you are talking about **overlapping** sparse group lasso, then my package cannot handle it. If just for non-overlapping sparse group lasso, the package [grpreg](https://cran.r-project.org/web/packages/grpreg/grpreg.pdf) is exactly what you want.

**Comment by ZoeTan** [comment]
Hi, Dr. Zeng

Thanks for your kindly reply and suggestions.

I just want to run the non-overlapping sparse group lasso. I read the details  of package grpreg. But I cannot find the right penalty argument for non-overlapping sparse group lasso. 

As described in the package manual, The grLasso, grMCP, and grSCAD penalties carry out group selection, while the gel and cMCP penalties carry out bi-level selection. 

Sparse group lasso performs bi-level selection. So, how to select the penalty in package grpreg.

Please give me some suggestions. I am working on this for several weeks. I run packages SGL for non-overlapping sparse group lasso. But the speed is too slow.

Thanks very much.

Zaixiang Tang

**Comment by YaohuiZeng** [comment]
Hi Zoe, then you use "cMCP" or "gel" for sparse group lasso.  As for the difference between the two, to be honest I am not sure. You may want to consult Patrick Breheny, the author of "grpreg". Or you can take a look at the reference papers in the manual. Good luck.

**Comment by ZoeTan** [comment]
Thanks for your quick response. "cMCP" or "gel" are for bi-level selection. it is different from the algorithm of sparse group lasso(SGL), developed by SIMON (2009) and Friedman(2010).

**Comment by YaohuiZeng** [comment]
Yes the algorithm is different due to different penalties. But 'cMCP' and 'gel' in `grpreg` also do sparse group selection: select important groups as well as important variables within selected groups. 

But if you want exactly the SGL by SIMON, I don't think 'grpreg' is what you want.

**Comment by ZoeTan** [comment]
you are right, thank you anyway.
